server:
  port: 9090

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: scott
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
   
  mvc:
    view:
      prefix: /views/
      suffix: .jsp 
  mail:
    host: smtp.gmail.com
    port: 587
    username: swapnilthakre2@gmail.com
    password: yatharth16
    properties:
             mail: 
                smtp:   
                  starttls:
                    enable: true
                  auth: true  
                  ssl:
                    trust: smtp.gmail.com    